allowBuilds:
  '@carbon/colors': false
  '@carbon/feature-flags': false
  '@carbon/grid': false
  '@carbon/icon-helpers': false
  '@carbon/icons-react': false
  '@carbon/layout': false
  '@carbon/motion': false
  '@carbon/react': false
  '@carbon/styles': false
  '@carbon/themes': false
  '@carbon/type': false
  '@carbon/utilities': false
  '@ibm/plex': false
  '@ibm/plex-mono': false
  '@ibm/plex-sans': false
  '@ibm/plex-sans-arabic': false
  '@ibm/plex-sans-devanagari': false
  '@ibm/plex-sans-hebrew': false
  '@ibm/plex-sans-thai': false
  '@ibm/plex-sans-thai-looped': false
  '@ibm/plex-serif': false
  '@parcel/watcher': false
  core-js: false
  esbuild: true
  lightningcss: true
  unrs-resolver: false
auditConfig:
  ignoreGhsas:
    - GHSA-vfj7-8cjw-p6xm
packages:
  - mocks/*
