/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedInRouteImport } from './routes/_signed-in'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignedInIndexRouteImport } from './routes/_signed-in.index'
import { Route as SignedInProductRouteImport } from './routes/_signed-in.$product'
import { Route as SignedInProductIndexRouteImport } from './routes/_signed-in.$product.index'
import { Route as ApiCronMeasureRouteImport } from './routes/api/cron.measure'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1.openapi[.]json'
import { Route as SignedInProductConceptRecordIdRouteImport } from './routes/_signed-in.$product.concept.$recordId'
import { Route as SignedInProductDecisionsNewRouteImport } from './routes/_signed-in.$product.decisions.new'
import { Route as ApiV1ProductsProductFolderRouteImport } from './routes/api/v1.products.$product.$folder'
import { Route as ApiV1ProductsProductConceptRouteImport } from './routes/api/v1.products.$product.concept'
import { Route as ApiV1ProductsProductMeasureRouteImport } from './routes/api/v1.products.$product.measure'
import { Route as ApiV1ProjectsProjectIndexRouteImport } from './routes/api/v1.projects.$project.index'
import { Route as ApiV1ProjectsProjectFolderRouteImport } from './routes/api/v1.projects.$project.$folder'
import { Route as ApiV1ProjectsProjectConceptRouteImport } from './routes/api/v1.projects.$project.concept'
import { Route as ApiV1ProjectsProjectConceptsRouteImport } from './routes/api/v1.projects.$project.concepts'
import { Route as ApiV1ProjectsProjectJointsRouteImport } from './routes/api/v1.projects.$project.joints'
import { Route as ApiV1ProjectsProjectMeasureRouteImport } from './routes/api/v1.projects.$project.measure'
import { Route as ApiV1ProjectsProjectPartsRouteImport } from './routes/api/v1.projects.$project.parts'
import { Route as ApiV1ProductsProductFolderRecordIdRouteImport } from './routes/api/v1.products.$product.$folder.$recordId'
import { Route as ApiV1ProjectsProjectFolderRecordIdRouteImport } from './routes/api/v1.projects.$project.$folder.$recordId'
import { Route as ApiV1ProjectsProjectConceptsConceptRouteImport } from './routes/api/v1.projects.$project.concepts.$concept'
import { Route as ApiV1ProjectsProjectJointsJointIdRouteImport } from './routes/api/v1.projects.$project.joints.$jointId'
import { Route as ApiV1ProjectsProjectPartsRecordIdRouteImport } from './routes/api/v1.projects.$project.parts.$recordId'

const SignedInRoute = SignedInRouteImport.update({
  id: '/_signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInIndexRoute = SignedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInRoute,
} as any)
const SignedInProductRoute = SignedInProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => SignedInRoute,
} as any)
const SignedInProductIndexRoute = SignedInProductIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInProductRoute,
} as any)
const ApiCronMeasureRoute = ApiCronMeasureRouteImport.update({
  id: '/api/cron/measure',
  path: '/api/cron/measure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInProductConceptRecordIdRoute =
  SignedInProductConceptRecordIdRouteImport.update({
    id: '/concept/$recordId',
    path: '/concept/$recordId',
    getParentRoute: () => SignedInProductRoute,
  } as any)
const SignedInProductDecisionsNewRoute =
  SignedInProductDecisionsNewRouteImport.update({
    id: '/decisions/new',
    path: '/decisions/new',
    getParentRoute: () => SignedInProductRoute,
  } as any)
const ApiV1ProductsProductFolderRoute =
  ApiV1ProductsProductFolderRouteImport.update({
    id: '/api/v1/products/$product/$folder',
    path: '/api/v1/products/$product/$folder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProductsProductConceptRoute =
  ApiV1ProductsProductConceptRouteImport.update({
    id: '/api/v1/products/$product/concept',
    path: '/api/v1/products/$product/concept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProductsProductMeasureRoute =
  ApiV1ProductsProductMeasureRouteImport.update({
    id: '/api/v1/products/$product/measure',
    path: '/api/v1/products/$product/measure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectIndexRoute =
  ApiV1ProjectsProjectIndexRouteImport.update({
    id: '/api/v1/projects/$project/',
    path: '/api/v1/projects/$project/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectFolderRoute =
  ApiV1ProjectsProjectFolderRouteImport.update({
    id: '/api/v1/projects/$project/$folder',
    path: '/api/v1/projects/$project/$folder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectConceptRoute =
  ApiV1ProjectsProjectConceptRouteImport.update({
    id: '/api/v1/projects/$project/concept',
    path: '/api/v1/projects/$project/concept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectConceptsRoute =
  ApiV1ProjectsProjectConceptsRouteImport.update({
    id: '/api/v1/projects/$project/concepts',
    path: '/api/v1/projects/$project/concepts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectJointsRoute =
  ApiV1ProjectsProjectJointsRouteImport.update({
    id: '/api/v1/projects/$project/joints',
    path: '/api/v1/projects/$project/joints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectMeasureRoute =
  ApiV1ProjectsProjectMeasureRouteImport.update({
    id: '/api/v1/projects/$project/measure',
    path: '/api/v1/projects/$project/measure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectPartsRoute =
  ApiV1ProjectsProjectPartsRouteImport.update({
    id: '/api/v1/projects/$project/parts',
    path: '/api/v1/projects/$project/parts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProductsProductFolderRecordIdRoute =
  ApiV1ProductsProductFolderRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => ApiV1ProductsProductFolderRoute,
  } as any)
const ApiV1ProjectsProjectFolderRecordIdRoute =
  ApiV1ProjectsProjectFolderRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => ApiV1ProjectsProjectFolderRoute,
  } as any)
const ApiV1ProjectsProjectConceptsConceptRoute =
  ApiV1ProjectsProjectConceptsConceptRouteImport.update({
    id: '/$concept',
    path: '/$concept',
    getParentRoute: () => ApiV1ProjectsProjectConceptsRoute,
  } as any)
const ApiV1ProjectsProjectJointsJointIdRoute =
  ApiV1ProjectsProjectJointsJointIdRouteImport.update({
    id: '/$jointId',
    path: '/$jointId',
    getParentRoute: () => ApiV1ProjectsProjectJointsRoute,
  } as any)
const ApiV1ProjectsProjectPartsRecordIdRoute =
  ApiV1ProjectsProjectPartsRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => ApiV1ProjectsProjectPartsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SignedInIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$product': typeof SignedInProductRouteWithChildren
  '/api/cron/measure': typeof ApiCronMeasureRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/$product/': typeof SignedInProductIndexRoute
  '/$product/concept/$recordId': typeof SignedInProductConceptRecordIdRoute
  '/$product/decisions/new': typeof SignedInProductDecisionsNewRoute
  '/api/v1/products/$product/$folder': typeof ApiV1ProductsProductFolderRouteWithChildren
  '/api/v1/products/$product/concept': typeof ApiV1ProductsProductConceptRoute
  '/api/v1/products/$product/measure': typeof ApiV1ProductsProductMeasureRoute
  '/api/v1/projects/$project/$folder': typeof ApiV1ProjectsProjectFolderRouteWithChildren
  '/api/v1/projects/$project/concept': typeof ApiV1ProjectsProjectConceptRoute
  '/api/v1/projects/$project/concepts': typeof ApiV1ProjectsProjectConceptsRouteWithChildren
  '/api/v1/projects/$project/joints': typeof ApiV1ProjectsProjectJointsRouteWithChildren
  '/api/v1/projects/$project/measure': typeof ApiV1ProjectsProjectMeasureRoute
  '/api/v1/projects/$project/parts': typeof ApiV1ProjectsProjectPartsRouteWithChildren
  '/api/v1/projects/$project/': typeof ApiV1ProjectsProjectIndexRoute
  '/api/v1/products/$product/$folder/$recordId': typeof ApiV1ProductsProductFolderRecordIdRoute
  '/api/v1/projects/$project/$folder/$recordId': typeof ApiV1ProjectsProjectFolderRecordIdRoute
  '/api/v1/projects/$project/concepts/$concept': typeof ApiV1ProjectsProjectConceptsConceptRoute
  '/api/v1/projects/$project/joints/$jointId': typeof ApiV1ProjectsProjectJointsJointIdRoute
  '/api/v1/projects/$project/parts/$recordId': typeof ApiV1ProjectsProjectPartsRecordIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/': typeof SignedInIndexRoute
  '/api/cron/measure': typeof ApiCronMeasureRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/$product': typeof SignedInProductIndexRoute
  '/$product/concept/$recordId': typeof SignedInProductConceptRecordIdRoute
  '/$product/decisions/new': typeof SignedInProductDecisionsNewRoute
  '/api/v1/products/$product/$folder': typeof ApiV1ProductsProductFolderRouteWithChildren
  '/api/v1/products/$product/concept': typeof ApiV1ProductsProductConceptRoute
  '/api/v1/products/$product/measure': typeof ApiV1ProductsProductMeasureRoute
  '/api/v1/projects/$project/$folder': typeof ApiV1ProjectsProjectFolderRouteWithChildren
  '/api/v1/projects/$project/concept': typeof ApiV1ProjectsProjectConceptRoute
  '/api/v1/projects/$project/concepts': typeof ApiV1ProjectsProjectConceptsRouteWithChildren
  '/api/v1/projects/$project/joints': typeof ApiV1ProjectsProjectJointsRouteWithChildren
  '/api/v1/projects/$project/measure': typeof ApiV1ProjectsProjectMeasureRoute
  '/api/v1/projects/$project/parts': typeof ApiV1ProjectsProjectPartsRouteWithChildren
  '/api/v1/projects/$project': typeof ApiV1ProjectsProjectIndexRoute
  '/api/v1/products/$product/$folder/$recordId': typeof ApiV1ProductsProductFolderRecordIdRoute
  '/api/v1/projects/$project/$folder/$recordId': typeof ApiV1ProjectsProjectFolderRecordIdRoute
  '/api/v1/projects/$project/concepts/$concept': typeof ApiV1ProjectsProjectConceptsConceptRoute
  '/api/v1/projects/$project/joints/$jointId': typeof ApiV1ProjectsProjectJointsJointIdRoute
  '/api/v1/projects/$project/parts/$recordId': typeof ApiV1ProjectsProjectPartsRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed-in': typeof SignedInRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_signed-in/$product': typeof SignedInProductRouteWithChildren
  '/_signed-in/': typeof SignedInIndexRoute
  '/api/cron/measure': typeof ApiCronMeasureRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/_signed-in/$product/': typeof SignedInProductIndexRoute
  '/_signed-in/$product/concept/$recordId': typeof SignedInProductConceptRecordIdRoute
  '/_signed-in/$product/decisions/new': typeof SignedInProductDecisionsNewRoute
  '/api/v1/products/$product/$folder': typeof ApiV1ProductsProductFolderRouteWithChildren
  '/api/v1/products/$product/concept': typeof ApiV1ProductsProductConceptRoute
  '/api/v1/products/$product/measure': typeof ApiV1ProductsProductMeasureRoute
  '/api/v1/projects/$project/$folder': typeof ApiV1ProjectsProjectFolderRouteWithChildren
  '/api/v1/projects/$project/concept': typeof ApiV1ProjectsProjectConceptRoute
  '/api/v1/projects/$project/concepts': typeof ApiV1ProjectsProjectConceptsRouteWithChildren
  '/api/v1/projects/$project/joints': typeof ApiV1ProjectsProjectJointsRouteWithChildren
  '/api/v1/projects/$project/measure': typeof ApiV1ProjectsProjectMeasureRoute
  '/api/v1/projects/$project/parts': typeof ApiV1ProjectsProjectPartsRouteWithChildren
  '/api/v1/projects/$project/': typeof ApiV1ProjectsProjectIndexRoute
  '/api/v1/products/$product/$folder/$recordId': typeof ApiV1ProductsProductFolderRecordIdRoute
  '/api/v1/projects/$project/$folder/$recordId': typeof ApiV1ProjectsProjectFolderRecordIdRoute
  '/api/v1/projects/$project/concepts/$concept': typeof ApiV1ProjectsProjectConceptsConceptRoute
  '/api/v1/projects/$project/joints/$jointId': typeof ApiV1ProjectsProjectJointsJointIdRoute
  '/api/v1/projects/$project/parts/$recordId': typeof ApiV1ProjectsProjectPartsRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/$product'
    | '/api/cron/measure'
    | '/api/v1/openapi.json'
    | '/$product/'
    | '/$product/concept/$recordId'
    | '/$product/decisions/new'
    | '/api/v1/products/$product/$folder'
    | '/api/v1/products/$product/concept'
    | '/api/v1/products/$product/measure'
    | '/api/v1/projects/$project/$folder'
    | '/api/v1/projects/$project/concept'
    | '/api/v1/projects/$project/concepts'
    | '/api/v1/projects/$project/joints'
    | '/api/v1/projects/$project/measure'
    | '/api/v1/projects/$project/parts'
    | '/api/v1/projects/$project/'
    | '/api/v1/products/$product/$folder/$recordId'
    | '/api/v1/projects/$project/$folder/$recordId'
    | '/api/v1/projects/$project/concepts/$concept'
    | '/api/v1/projects/$project/joints/$jointId'
    | '/api/v1/projects/$project/parts/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/api/cron/measure'
    | '/api/v1/openapi.json'
    | '/$product'
    | '/$product/concept/$recordId'
    | '/$product/decisions/new'
    | '/api/v1/products/$product/$folder'
    | '/api/v1/products/$product/concept'
    | '/api/v1/products/$product/measure'
    | '/api/v1/projects/$project/$folder'
    | '/api/v1/projects/$project/concept'
    | '/api/v1/projects/$project/concepts'
    | '/api/v1/projects/$project/joints'
    | '/api/v1/projects/$project/measure'
    | '/api/v1/projects/$project/parts'
    | '/api/v1/projects/$project'
    | '/api/v1/products/$product/$folder/$recordId'
    | '/api/v1/projects/$project/$folder/$recordId'
    | '/api/v1/projects/$project/concepts/$concept'
    | '/api/v1/projects/$project/joints/$jointId'
    | '/api/v1/projects/$project/parts/$recordId'
  id:
    | '__root__'
    | '/_signed-in'
    | '/sign-in'
    | '/sign-up'
    | '/_signed-in/$product'
    | '/_signed-in/'
    | '/api/cron/measure'
    | '/api/v1/openapi.json'
    | '/_signed-in/$product/'
    | '/_signed-in/$product/concept/$recordId'
    | '/_signed-in/$product/decisions/new'
    | '/api/v1/products/$product/$folder'
    | '/api/v1/products/$product/concept'
    | '/api/v1/products/$product/measure'
    | '/api/v1/projects/$project/$folder'
    | '/api/v1/projects/$project/concept'
    | '/api/v1/projects/$project/concepts'
    | '/api/v1/projects/$project/joints'
    | '/api/v1/projects/$project/measure'
    | '/api/v1/projects/$project/parts'
    | '/api/v1/projects/$project/'
    | '/api/v1/products/$product/$folder/$recordId'
    | '/api/v1/projects/$project/$folder/$recordId'
    | '/api/v1/projects/$project/concepts/$concept'
    | '/api/v1/projects/$project/joints/$jointId'
    | '/api/v1/projects/$project/parts/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignedInRoute: typeof SignedInRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiCronMeasureRoute: typeof ApiCronMeasureRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1ProductsProductFolderRoute: typeof ApiV1ProductsProductFolderRouteWithChildren
  ApiV1ProductsProductConceptRoute: typeof ApiV1ProductsProductConceptRoute
  ApiV1ProductsProductMeasureRoute: typeof ApiV1ProductsProductMeasureRoute
  ApiV1ProjectsProjectFolderRoute: typeof ApiV1ProjectsProjectFolderRouteWithChildren
  ApiV1ProjectsProjectConceptRoute: typeof ApiV1ProjectsProjectConceptRoute
  ApiV1ProjectsProjectConceptsRoute: typeof ApiV1ProjectsProjectConceptsRouteWithChildren
  ApiV1ProjectsProjectJointsRoute: typeof ApiV1ProjectsProjectJointsRouteWithChildren
  ApiV1ProjectsProjectMeasureRoute: typeof ApiV1ProjectsProjectMeasureRoute
  ApiV1ProjectsProjectPartsRoute: typeof ApiV1ProjectsProjectPartsRouteWithChildren
  ApiV1ProjectsProjectIndexRoute: typeof ApiV1ProjectsProjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed-in': {
      id: '/_signed-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed-in/': {
      id: '/_signed-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SignedInIndexRouteImport
      parentRoute: typeof SignedInRoute
    }
    '/_signed-in/$product': {
      id: '/_signed-in/$product'
      path: '/$product'
      fullPath: '/$product'
      preLoaderRoute: typeof SignedInProductRouteImport
      parentRoute: typeof SignedInRoute
    }
    '/_signed-in/$product/': {
      id: '/_signed-in/$product/'
      path: '/'
      fullPath: '/$product/'
      preLoaderRoute: typeof SignedInProductIndexRouteImport
      parentRoute: typeof SignedInProductRoute
    }
    '/api/cron/measure': {
      id: '/api/cron/measure'
      path: '/api/cron/measure'
      fullPath: '/api/cron/measure'
      preLoaderRoute: typeof ApiCronMeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed-in/$product/concept/$recordId': {
      id: '/_signed-in/$product/concept/$recordId'
      path: '/concept/$recordId'
      fullPath: '/$product/concept/$recordId'
      preLoaderRoute: typeof SignedInProductConceptRecordIdRouteImport
      parentRoute: typeof SignedInProductRoute
    }
    '/_signed-in/$product/decisions/new': {
      id: '/_signed-in/$product/decisions/new'
      path: '/decisions/new'
      fullPath: '/$product/decisions/new'
      preLoaderRoute: typeof SignedInProductDecisionsNewRouteImport
      parentRoute: typeof SignedInProductRoute
    }
    '/api/v1/products/$product/$folder': {
      id: '/api/v1/products/$product/$folder'
      path: '/api/v1/products/$product/$folder'
      fullPath: '/api/v1/products/$product/$folder'
      preLoaderRoute: typeof ApiV1ProductsProductFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/$product/concept': {
      id: '/api/v1/products/$product/concept'
      path: '/api/v1/products/$product/concept'
      fullPath: '/api/v1/products/$product/concept'
      preLoaderRoute: typeof ApiV1ProductsProductConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/$product/measure': {
      id: '/api/v1/products/$product/measure'
      path: '/api/v1/products/$product/measure'
      fullPath: '/api/v1/products/$product/measure'
      preLoaderRoute: typeof ApiV1ProductsProductMeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/': {
      id: '/api/v1/projects/$project/'
      path: '/api/v1/projects/$project'
      fullPath: '/api/v1/projects/$project/'
      preLoaderRoute: typeof ApiV1ProjectsProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/$folder': {
      id: '/api/v1/projects/$project/$folder'
      path: '/api/v1/projects/$project/$folder'
      fullPath: '/api/v1/projects/$project/$folder'
      preLoaderRoute: typeof ApiV1ProjectsProjectFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/concept': {
      id: '/api/v1/projects/$project/concept'
      path: '/api/v1/projects/$project/concept'
      fullPath: '/api/v1/projects/$project/concept'
      preLoaderRoute: typeof ApiV1ProjectsProjectConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/concepts': {
      id: '/api/v1/projects/$project/concepts'
      path: '/api/v1/projects/$project/concepts'
      fullPath: '/api/v1/projects/$project/concepts'
      preLoaderRoute: typeof ApiV1ProjectsProjectConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/joints': {
      id: '/api/v1/projects/$project/joints'
      path: '/api/v1/projects/$project/joints'
      fullPath: '/api/v1/projects/$project/joints'
      preLoaderRoute: typeof ApiV1ProjectsProjectJointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/measure': {
      id: '/api/v1/projects/$project/measure'
      path: '/api/v1/projects/$project/measure'
      fullPath: '/api/v1/projects/$project/measure'
      preLoaderRoute: typeof ApiV1ProjectsProjectMeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$project/parts': {
      id: '/api/v1/projects/$project/parts'
      path: '/api/v1/projects/$project/parts'
      fullPath: '/api/v1/projects/$project/parts'
      preLoaderRoute: typeof ApiV1ProjectsProjectPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/$product/$folder/$recordId': {
      id: '/api/v1/products/$product/$folder/$recordId'
      path: '/$recordId'
      fullPath: '/api/v1/products/$product/$folder/$recordId'
      preLoaderRoute: typeof ApiV1ProductsProductFolderRecordIdRouteImport
      parentRoute: typeof ApiV1ProductsProductFolderRoute
    }
    '/api/v1/projects/$project/$folder/$recordId': {
      id: '/api/v1/projects/$project/$folder/$recordId'
      path: '/$recordId'
      fullPath: '/api/v1/projects/$project/$folder/$recordId'
      preLoaderRoute: typeof ApiV1ProjectsProjectFolderRecordIdRouteImport
      parentRoute: typeof ApiV1ProjectsProjectFolderRoute
    }
    '/api/v1/projects/$project/concepts/$concept': {
      id: '/api/v1/projects/$project/concepts/$concept'
      path: '/$concept'
      fullPath: '/api/v1/projects/$project/concepts/$concept'
      preLoaderRoute: typeof ApiV1ProjectsProjectConceptsConceptRouteImport
      parentRoute: typeof ApiV1ProjectsProjectConceptsRoute
    }
    '/api/v1/projects/$project/joints/$jointId': {
      id: '/api/v1/projects/$project/joints/$jointId'
      path: '/$jointId'
      fullPath: '/api/v1/projects/$project/joints/$jointId'
      preLoaderRoute: typeof ApiV1ProjectsProjectJointsJointIdRouteImport
      parentRoute: typeof ApiV1ProjectsProjectJointsRoute
    }
    '/api/v1/projects/$project/parts/$recordId': {
      id: '/api/v1/projects/$project/parts/$recordId'
      path: '/$recordId'
      fullPath: '/api/v1/projects/$project/parts/$recordId'
      preLoaderRoute: typeof ApiV1ProjectsProjectPartsRecordIdRouteImport
      parentRoute: typeof ApiV1ProjectsProjectPartsRoute
    }
  }
}

interface SignedInProductRouteChildren {
  SignedInProductIndexRoute: typeof SignedInProductIndexRoute
  SignedInProductConceptRecordIdRoute: typeof SignedInProductConceptRecordIdRoute
  SignedInProductDecisionsNewRoute: typeof SignedInProductDecisionsNewRoute
}

const SignedInProductRouteChildren: SignedInProductRouteChildren = {
  SignedInProductIndexRoute: SignedInProductIndexRoute,
  SignedInProductConceptRecordIdRoute: SignedInProductConceptRecordIdRoute,
  SignedInProductDecisionsNewRoute: SignedInProductDecisionsNewRoute,
}

const SignedInProductRouteWithChildren = SignedInProductRoute._addFileChildren(
  SignedInProductRouteChildren,
)

interface SignedInRouteChildren {
  SignedInProductRoute: typeof SignedInProductRouteWithChildren
  SignedInIndexRoute: typeof SignedInIndexRoute
}

const SignedInRouteChildren: SignedInRouteChildren = {
  SignedInProductRoute: SignedInProductRouteWithChildren,
  SignedInIndexRoute: SignedInIndexRoute,
}

const SignedInRouteWithChildren = SignedInRoute._addFileChildren(
  SignedInRouteChildren,
)

interface ApiV1ProductsProductFolderRouteChildren {
  ApiV1ProductsProductFolderRecordIdRoute: typeof ApiV1ProductsProductFolderRecordIdRoute
}

const ApiV1ProductsProductFolderRouteChildren: ApiV1ProductsProductFolderRouteChildren =
  {
    ApiV1ProductsProductFolderRecordIdRoute:
      ApiV1ProductsProductFolderRecordIdRoute,
  }

const ApiV1ProductsProductFolderRouteWithChildren =
  ApiV1ProductsProductFolderRoute._addFileChildren(
    ApiV1ProductsProductFolderRouteChildren,
  )

interface ApiV1ProjectsProjectFolderRouteChildren {
  ApiV1ProjectsProjectFolderRecordIdRoute: typeof ApiV1ProjectsProjectFolderRecordIdRoute
}

const ApiV1ProjectsProjectFolderRouteChildren: ApiV1ProjectsProjectFolderRouteChildren =
  {
    ApiV1ProjectsProjectFolderRecordIdRoute:
      ApiV1ProjectsProjectFolderRecordIdRoute,
  }

const ApiV1ProjectsProjectFolderRouteWithChildren =
  ApiV1ProjectsProjectFolderRoute._addFileChildren(
    ApiV1ProjectsProjectFolderRouteChildren,
  )

interface ApiV1ProjectsProjectConceptsRouteChildren {
  ApiV1ProjectsProjectConceptsConceptRoute: typeof ApiV1ProjectsProjectConceptsConceptRoute
}

const ApiV1ProjectsProjectConceptsRouteChildren: ApiV1ProjectsProjectConceptsRouteChildren =
  {
    ApiV1ProjectsProjectConceptsConceptRoute:
      ApiV1ProjectsProjectConceptsConceptRoute,
  }

const ApiV1ProjectsProjectConceptsRouteWithChildren =
  ApiV1ProjectsProjectConceptsRoute._addFileChildren(
    ApiV1ProjectsProjectConceptsRouteChildren,
  )

interface ApiV1ProjectsProjectJointsRouteChildren {
  ApiV1ProjectsProjectJointsJointIdRoute: typeof ApiV1ProjectsProjectJointsJointIdRoute
}

const ApiV1ProjectsProjectJointsRouteChildren: ApiV1ProjectsProjectJointsRouteChildren =
  {
    ApiV1ProjectsProjectJointsJointIdRoute:
      ApiV1ProjectsProjectJointsJointIdRoute,
  }

const ApiV1ProjectsProjectJointsRouteWithChildren =
  ApiV1ProjectsProjectJointsRoute._addFileChildren(
    ApiV1ProjectsProjectJointsRouteChildren,
  )

interface ApiV1ProjectsProjectPartsRouteChildren {
  ApiV1ProjectsProjectPartsRecordIdRoute: typeof ApiV1ProjectsProjectPartsRecordIdRoute
}

const ApiV1ProjectsProjectPartsRouteChildren: ApiV1ProjectsProjectPartsRouteChildren =
  {
    ApiV1ProjectsProjectPartsRecordIdRoute:
      ApiV1ProjectsProjectPartsRecordIdRoute,
  }

const ApiV1ProjectsProjectPartsRouteWithChildren =
  ApiV1ProjectsProjectPartsRoute._addFileChildren(
    ApiV1ProjectsProjectPartsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SignedInRoute: SignedInRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiCronMeasureRoute: ApiCronMeasureRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1ProductsProductFolderRoute: ApiV1ProductsProductFolderRouteWithChildren,
  ApiV1ProductsProductConceptRoute: ApiV1ProductsProductConceptRoute,
  ApiV1ProductsProductMeasureRoute: ApiV1ProductsProductMeasureRoute,
  ApiV1ProjectsProjectFolderRoute: ApiV1ProjectsProjectFolderRouteWithChildren,
  ApiV1ProjectsProjectConceptRoute: ApiV1ProjectsProjectConceptRoute,
  ApiV1ProjectsProjectConceptsRoute:
    ApiV1ProjectsProjectConceptsRouteWithChildren,
  ApiV1ProjectsProjectJointsRoute: ApiV1ProjectsProjectJointsRouteWithChildren,
  ApiV1ProjectsProjectMeasureRoute: ApiV1ProjectsProjectMeasureRoute,
  ApiV1ProjectsProjectPartsRoute: ApiV1ProjectsProjectPartsRouteWithChildren,
  ApiV1ProjectsProjectIndexRoute: ApiV1ProjectsProjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
